"""aModificando atributos da tabela e adicionando enum

Revision ID: 20740959c497
Revises: c0f54cac2722
Create Date: 2026-05-27 21:44:15.320413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20740959c497'
down_revision: Union[str, Sequence[str], None] = 'c0f54cac2722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum(
    'AGUARDANDO_ANALISE',
    'APROVADO',
    'RECUSADO',
    name='statusenum'
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    
    op.execute("""
        ALTER TABLE clientes
        ALTER COLUMN status
        TYPE statusenum
        USING status::statusenum
    """)
    op.alter_column('clientes', 'prioridade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'prioridade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'status',
               existing_type=sa.Enum('AGUARDANDO_ANALISE', 'APROVADO', 'RECUSADO', name='statusenum'),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
