"""atualizando enum status

Revision ID: 4019e13fee75
Revises: d2cb34fc120b
Create Date: 2026-05-28 14:02:20.435732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4019e13fee75'
down_revision: Union[str, Sequence[str], None] = 'd2cb34fc120b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum(
    'AGUARDANDO_ANALISE',
    'PROCESSADO',
    name='statusenum'
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    
    op.execute("""
            ALTER TYPE statusenum
            ADD VALUE 'PROCESSADO'
            """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
