"""Adicionando foreignkey na tablea webhook

Revision ID: 7f07ac9b490f
Revises: 4019e13fee75
Create Date: 2026-05-28 15:36:05.259530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f07ac9b490f'
down_revision: Union[str, Sequence[str], None] = '4019e13fee75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'webhook', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook', type_='foreignkey')
    op.drop_column('webhook', 'cliente_id')
    # ### end Alembic commands ###
