"""alterando nome das colunas: nome e email

Revision ID: c0f54cac2722
Revises: a0bed94ea419
Create Date: 2026-05-27 18:57:02.888977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f54cac2722'
down_revision: Union[str, Sequence[str], None] = 'a0bed94ea419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cliente_nome', sa.String(), nullable=False))
    op.add_column('clientes', sa.Column('cliente_email', sa.String(), nullable=False))
    op.drop_constraint(op.f('clientes_email_key'), 'clientes', type_='unique')
    op.create_unique_constraint(None, 'clientes', ['cliente_email'])
    op.drop_column('clientes', 'email')
    op.drop_column('clientes', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clientes', type_='unique')
    op.create_unique_constraint(op.f('clientes_email_key'), 'clientes', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('clientes', 'cliente_email')
    op.drop_column('clientes', 'cliente_nome')
    # ### end Alembic commands ###
